#!/usr/bin/env python3
"""
build_bundle.py — Bundles all debate and attendee JSON files into a single JS file.
This allows the site to work when opened directly via file:// in a browser,
without needing a local HTTP server.

Usage:
  python3 scripts/build_bundle.py

Output: data/data-bundle.js
"""

import hashlib
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR.parent / 'data'
OUT_FILE = DATA_DIR / 'data-bundle.js'


def main():
    manifest_path = DATA_DIR / 'manifest.json'
    if not manifest_path.exists():
        print('ERROR: data/manifest.json not found. Run the scraper first.')
        sys.exit(1)

    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    days = manifest.get('days', [])
    print(f'Building bundle from {len(days)} debate days...')

    debates = {}
    missing = []
    for day in days:
        day_path = DATA_DIR / day['file']
        if not day_path.exists():
            missing.append(day['id'])
            continue
        debates[day['id']] = json.loads(day_path.read_text(encoding='utf-8'))

    if missing:
        print(f'WARNING: {len(missing)} missing files: {", ".join(missing)}')

    manifest_json = json.dumps(manifest, ensure_ascii=False)
    debates_json = json.dumps(debates, ensure_ascii=False)

    # --- Attendees ---
    attendees_dir = DATA_DIR / 'attendees'
    attendees_manifest_path = attendees_dir / 'attendees.json'
    attendees_data = {}
    attendees_manifest_json = '[]'
    if attendees_manifest_path.exists():
        card_list = json.loads(attendees_manifest_path.read_text(encoding='utf-8'))
        attendees_manifest_json = json.dumps(card_list, ensure_ascii=False)
        for card in card_list:
            profile_path = attendees_dir / f'attendee_{card["id"]}.json'
            if profile_path.exists():
                attendees_data[card['id']] = json.loads(profile_path.read_text(encoding='utf-8'))
        print(f'Bundling {len(attendees_data)} attendee profiles...')
    else:
        print('NOTE: data/attendees/attendees.json not found — skipping attendees bundle')
    attendees_data_json = json.dumps(attendees_data, ensure_ascii=False)

    # --- Books ---
    books_path = DATA_DIR / 'books.json'
    books_json = '{}'
    if books_path.exists():
        books_json = books_path.read_text(encoding='utf-8')
        print('Bundling books data...')
    else:
        print('NOTE: data/books.json not found — skipping books bundle')

    bundle = f"""// data-bundle.js — auto-generated by scripts/build_bundle.py
// Contains all debate, attendee, and books data as JS globals so the site works on file:// protocol.
// DO NOT edit manually — re-run build_bundle.py to regenerate.
(function() {{
  window.__DEBATES_MANIFEST__ = {manifest_json};
  window.__DEBATES_DATA__ = {debates_json};
  window.__ATTENDEES_MANIFEST__ = {attendees_manifest_json};
  window.__ATTENDEES_DATA__ = {attendees_data_json};
  window.__BOOKS_DATA__ = {books_json};
}})();
"""

    OUT_FILE.write_text(bundle, encoding='utf-8')
    size_kb = OUT_FILE.stat().st_size / 1024
    print(f'✓ Written to data/data-bundle.js ({size_kb:.0f} KB, {len(debates)} days + {len(attendees_data)} attendees)')

    # Update cache-busting query string in all HTML files
    bundle_hash = hashlib.md5(OUT_FILE.read_bytes()).hexdigest()[:8]
    pattern = re.compile(r'(src="data/data-bundle\.js)(?:\?v=[^"]*)?(")')
    replacement = rf'\1?v={bundle_hash}\2'
    html_files = ['index.html', 'debates.html', 'attendees.html', 'attendee.html', 'books.html']
    for filename in html_files:
        path = SCRIPT_DIR.parent / filename
        if not path.exists():
            continue
        text = path.read_text(encoding='utf-8')
        new_text = pattern.sub(replacement, text)
        if new_text != text:
            path.write_text(new_text, encoding='utf-8')
            print(f'✓ Updated cache-bust token in {filename}')
    print(f'  Cache-bust hash: {bundle_hash}')


if __name__ == '__main__':
    main()
