#!/usr/bin/env python3
"""
build_bundle.py — Bundles all debate JSON files into a single JS file.
This allows the site to work when opened directly via file:// in a browser,
without needing a local HTTP server.

Usage:
  python3 scripts/build_bundle.py

Output: data/debates-bundle.js
"""

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR.parent / 'data'
OUT_FILE = DATA_DIR / 'debates-bundle.js'


def main():
    manifest_path = DATA_DIR / 'manifest.json'
    if not manifest_path.exists():
        print('ERROR: data/manifest.json not found. Run the scraper first.')
        sys.exit(1)

    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    days = manifest.get('days', [])
    print(f'Building bundle from {len(days)} debate days...')

    debates = {}
    missing = []
    for day in days:
        day_path = DATA_DIR / day['file']
        if not day_path.exists():
            missing.append(day['id'])
            continue
        debates[day['id']] = json.loads(day_path.read_text(encoding='utf-8'))

    if missing:
        print(f'WARNING: {len(missing)} missing files: {", ".join(missing)}')

    manifest_json = json.dumps(manifest, ensure_ascii=False)
    debates_json = json.dumps(debates, ensure_ascii=False)

    bundle = f"""// debates-bundle.js — auto-generated by scripts/build_bundle.py
// Contains all debate data as JS globals so the site works on file:// protocol.
// DO NOT edit manually — re-run build_bundle.py to regenerate.
(function() {{
  window.__DEBATES_MANIFEST__ = {manifest_json};
  window.__DEBATES_DATA__ = {debates_json};
}})();
"""

    OUT_FILE.write_text(bundle, encoding='utf-8')
    size_kb = OUT_FILE.stat().st_size / 1024
    print(f'✓ Written to data/debates-bundle.js ({size_kb:.0f} KB, {len(debates)} days)')


if __name__ == '__main__':
    main()
