#!/usr/bin/env python3
"""
link_delegates.py — Scans every debate's contentHtml and summary and wraps
delegate name mentions with <a class="delegate-link" data-attendee-id="…">
links.

Both fields are processed:
  • contentHtml  — uses 18th-century address forms ("Mr. Madison",
                   "Genl. Washington", "Docr. Franklin")
  • summary      — uses modern prose full names ("James Wilson") and bare
                   last names ("Gerry", "Ellsworth")

Safe to re-run: strips any existing delegate links before re-applying,
so the output is always a clean, single-pass result.

Usage:
    python3 scripts/link_delegates.py [--dry-run] [--stats]

    --dry-run   Report what would change without writing files.
    --stats     Print a link-count table sorted by delegate after processing.

After running, rebuild the bundle:
    python3 scripts/build_bundle.py
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA = ROOT / "data"

DRY_RUN    = "--dry-run" in sys.argv
SHOW_STATS = "--stats"   in sys.argv

# ──────────────────────────────────────────────────────────────────────────────
# Pattern table
#
# Each entry is (regex_string, delegate_id).
#
# Rules:
#   • All patterns are compiled with re.IGNORECASE, so a single pattern covers
#     both in-text mixed-case ("Mr. Madison") and all-caps speaker labels
#     ("Mr. MADISON").
#   • More-specific patterns MUST appear before less-specific ones
#     (e.g. C. C. Pinckney before generic Pinckney; qualified Morris forms
#     before bare "Mr. Morris").
#   • Spelling variants found across all 85 debate files are included
#     (Dickinson/Dickenson, Rutledge/Rutlidge, Gorham/Ghorum, etc.).
#   • Possessive forms ("Mr. Madison's") are handled automatically because
#     \b matches between the final letter and the apostrophe.
#
# IDs must match the slugs generated by fetch_attendees.py (see attendees.json).
# ──────────────────────────────────────────────────────────────────────────────

RAW_PATTERNS = [

    # ── Benjamin Franklin ────────────────────────────────────────────────────
    # Addressed as "Docr." (period variant of Doctor) in Madison's notes
    (r"Docr\.?\s+Franklin\b",               "benjamin_franklin"),
    (r"Dr\.?\s+Franklin\b",                 "benjamin_franklin"),
    (r"Mr\.?\s+Franklin\b",                 "benjamin_franklin"),

    # ── George Washington ────────────────────────────────────────────────────
    # Presided; usually "Genl. Washington" or "General Washington"
    (r"Genl?\.?\s+Washington\b",            "george_washington"),
    (r"General\s+Washington\b",             "george_washington"),
    (r"Mr\.?\s+Washington\b",               "george_washington"),

    # ── Alexander Hamilton ───────────────────────────────────────────────────
    # Often addressed by his wartime rank "Col."
    (r"Col\.?\s+Hamilton\b",                "alexander_hamilton"),
    (r"Mr\.?\s+Hamilton\b",                 "alexander_hamilton"),

    # ── James Madison Jr. ────────────────────────────────────────────────────
    (r"Mr\.?\s+Madison\b",                  "james_madison_jr"),

    # ── Gouverneur Morris ────────────────────────────────────────────────────
    # Must come before the generic "Mr. Morris" catch-all below.
    # Madison wrote his name several ways: "Govr. Morris", "Mr. Gouverneur",
    # "Mr. GOVERNR", "Mr. GOVERNUr", "Mr. Govr", etc.
    (r"Govr?\.?\s+Morris\b",                "gouverneur_morris"),
    (r"G\.?\s+Morris\b",                    "gouverneur_morris"),
    (r"Mr\.?\s+Govern(?:eur|r|nr|ur)?\b",   "gouverneur_morris"),
    (r"Mr\.?\s+Gouverneur\b",               "gouverneur_morris"),

    # ── Robert Morris ────────────────────────────────────────────────────────
    # Must come before generic "Mr. Morris"
    (r"Mr\.?\s+Rob(?:t|ert)\.?\s+Morris\b", "robert_morris"),

    # ── Generic "Mr. Morris" → Gouverneur ────────────────────────────────────
    # Gouverneur spoke far more; bare "Mr. Morris" almost always means him.
    (r"Mr\.?\s+Morris\b",                   "gouverneur_morris"),

    # ── Charles Cotesworth Pinckney ──────────────────────────────────────────
    # Addressed by his military rank "Genl." Must come before generic Pinckney.
    # Note: "Pinkney" / "Pinkeney" are period misspellings in the source text.
    (r"Genl?\.?\s+Pinck?(?:e?n)?ey?\b",     "charles_cotesworth_pinckney"),
    (r"General\s+Pinck?(?:e?n)?ey?\b",      "charles_cotesworth_pinckney"),

    # ── Charles Pinckney (generic) ───────────────────────────────────────────
    (r"Mr\.?\s+Chs\.?\s+Pinck?(?:e?n)?ey?\b", "charles_pinckney"),
    (r"Mr\.?\s+Pinck?(?:e?n)?ey?\b",           "charles_pinckney"),

    # ── James Wilson ─────────────────────────────────────────────────────────
    (r"Mr\.?\s+Wilson\b",                   "james_wilson"),

    # ── George Mason ─────────────────────────────────────────────────────────
    # Sometimes addressed as "Col. Mason"
    (r"Col\.?\s+Mas+on\b",                  "george_mason"),
    (r"Mr\.?\s+Mas+on\b",                   "george_mason"),

    # ── Roger Sherman ────────────────────────────────────────────────────────
    # "Sharman" and "Shareman" appear in source text
    (r"Mr\.?\s+Sher?man\b",                 "roger_sherman"),

    # ── Edmund J. Randolph ───────────────────────────────────────────────────
    # He was Governor of Virginia; "Govr. Randolph" also appears
    (r"Mr\.?\s+Randolp?h?\b",               "edmund_j_randolph"),
    (r"Govr?\.?\s+Randolph\b",              "edmund_j_randolph"),

    # ── Elbridge Gerry ───────────────────────────────────────────────────────
    (r"Mr\.?\s+Gerry\b",                    "elbridge_gerry"),

    # ── Rufus King ───────────────────────────────────────────────────────────
    (r"Mr\.?\s+King\b",                     "rufus_king"),

    # ── William Paterson ─────────────────────────────────────────────────────
    # "Patterson" (double-t) is the common period misspelling in source text
    (r"Mr\.?\s+Paters?on\b",                "william_paterson"),
    (r"Mr\.?\s+Patterson\b",                "william_paterson"),

    # ── John Dickinson ───────────────────────────────────────────────────────
    # "Dickenson" is the common period misspelling
    (r"Mr\.?\s+Dicke?n[sc]on\b",            "john_dickinson"),

    # ── Oliver Ellsworth ─────────────────────────────────────────────────────
    # Wildly inconsistent in source: Ellsworth, Elseworth, Elsworth,
    # Elsewth, Ellsewth, Elsewoth
    (r"Mr\.?\s+Ell?s(?:e?worth|ewth|woth)\b", "oliver_ellsworth"),

    # ── John Rutledge ────────────────────────────────────────────────────────
    # "Rutlidge" and "Rultidge" appear in source
    (r"Mr\.?\s+R(?:ut|ul)l?[ie]dge?\b",     "john_rutledge"),

    # ── William Samuel Johnson ───────────────────────────────────────────────
    # He held a doctorate; "Docr. Johnson" appears
    (r"Docr\.?\s+Johnson\b",                "william_samuel_johnson"),
    (r"Dr\.?\s+Johnson\b",                  "william_samuel_johnson"),
    (r"Mr\.?\s+Johnson\b",                  "william_samuel_johnson"),

    # ── Gunning Bedford Jr. ──────────────────────────────────────────────────
    (r"Mr\.?\s+Bedford\b",                  "gunning_bedford_jr"),

    # ── George Read ──────────────────────────────────────────────────────────
    # "Reed" and "Reid" appear as period spellings in source
    (r"Mr\.?\s+R[ée]e?d\b",                 "george_read"),

    # ── John Langdon ─────────────────────────────────────────────────────────
    (r"Mr\.?\s+Langdon\b",                  "john_langdon"),

    # ── Nathaniel Gorham ─────────────────────────────────────────────────────
    # "Ghorum" is the phonetic period misspelling in source text
    (r"Mr\.?\s+G(?:h?or|or)h?am\b",         "nathaniel_gorham"),

    # ── Hugh Williamson ──────────────────────────────────────────────────────
    # He was a physician; "Docr. Williamson" appears
    (r"Docr\.?\s+Williamson\b",             "hugh_williamson"),
    (r"Mr\.?\s+Willi?amsons?\b",            "hugh_williamson"),

    # ── Pierce Butler ────────────────────────────────────────────────────────
    (r"Mr\.?\s+Butler\b",                   "pierce_butler"),

    # ── Abraham Baldwin ──────────────────────────────────────────────────────
    (r"Mr\.?\s+Baldwin\b",                  "abraham_baldwin"),

    # ── William Blount ───────────────────────────────────────────────────────
    (r"Mr\.?\s+Blount\b",                   "william_blount"),

    # ── Richard Dobbs Spaight ────────────────────────────────────────────────
    (r"Mr\.?\s+Spaight\b",                  "richard_dobbs_spaight"),

    # ── George Clymer ────────────────────────────────────────────────────────
    (r"Mr\.?\s+Clymer\b",                   "george_clymer"),

    # ── Thomas Fitzsimons ────────────────────────────────────────────────────
    # "Fitzimmons" is the period misspelling in source text
    (r"Mr\.?\s+Fitz[Ii]m+ons?\b",           "thomas_fitzsimons"),

    # ── Jared Ingersoll ──────────────────────────────────────────────────────
    (r"Mr\.?\s+Ingersol+\b",                "jared_ingersoll"),

    # ── Thomas Mifflin ───────────────────────────────────────────────────────
    # He was a general; "Genl. Mifflin" appears
    (r"Genl?\.?\s+Mifflin\b",               "thomas_mifflin"),
    (r"Mr\.?\s+Mifflin\b",                  "thomas_mifflin"),

    # ── James McHenry ────────────────────────────────────────────────────────
    # "M'Henry" (with apostrophe) is an 18th-century Scots-Irish spelling
    (r"Mr\.?\s+M[c']?Henry\b",              "james_mchenry"),

    # ── Luther Martin ────────────────────────────────────────────────────────
    # "Mr. Luther Martin" also appears in full
    (r"Mr\.?\s+(?:Luther\s+)?Martin\b",     "luther_martin"),

    # ── Daniel Carroll ───────────────────────────────────────────────────────
    # "Carrol" (single-l) is the common period spelling
    (r"Mr\.?\s+Carrol+\b",                  "daniel_carroll"),

    # ── Daniel of St. Thomas Jenifer ─────────────────────────────────────────
    # "Jennifer" (double-n) appears as a period misspelling
    (r"Mr\.?\s+Jenife?r\b",                 "daniel_of_st_thomas_jenifer"),

    # ── John F. Mercer ───────────────────────────────────────────────────────
    (r"Mr\.?\s+Mercer\b",                   "john_f_mercer"),

    # ── William Few ──────────────────────────────────────────────────────────
    (r"Mr\.?\s+Few\b",                      "william_few"),

    # ── William L. Pierce ────────────────────────────────────────────────────
    (r"Mr\.?\s+Pierce\b",                   "william_l_pierce"),

    # ── Jonathan Dayton ──────────────────────────────────────────────────────
    (r"Mr\.?\s+Dayton\b",                   "jonathan_dayton"),

    # ── William Livingston ───────────────────────────────────────────────────
    # He was Governor of New Jersey; "Govr. Livingston" appears
    (r"Govr?\.?\s+Livingston\b",            "william_livingston"),
    (r"Mr\.?\s+Livingston\b",               "william_livingston"),

    # ── David Brearly ────────────────────────────────────────────────────────
    # "Brearley", "Breerly" found in source
    (r"Mr\.?\s+Brea?r[el]y\b",              "david_brearly"),

    # ── James McClurg ────────────────────────────────────────────────────────
    # He held a doctorate; "M'Clurg" is the period spelling
    (r"Dr\.?\s+McClurg\b",                  "james_mcclurg"),
    (r"Mr\.?\s+M[c']?Clurg\b",              "james_mcclurg"),

    # ── John Blair ───────────────────────────────────────────────────────────
    (r"Mr\.?\s+Blair\b",                    "john_blair"),

    # ── George Wythe ─────────────────────────────────────────────────────────
    (r"Mr\.?\s+Wythe\b",                    "george_wythe"),

    # ── Caleb Strong ─────────────────────────────────────────────────────────
    (r"Mr\.?\s+Strong\b",                   "caleb_strong"),

    # ── Nicholas Gilman ──────────────────────────────────────────────────────
    (r"Mr\.?\s+Gilman\b",                   "nicholas_gilman"),

    # ── John Lansing Jr. ─────────────────────────────────────────────────────
    (r"Mr\.?\s+Lansing\b",                  "john_lansing_jr"),

    # ── Robert Yates ─────────────────────────────────────────────────────────
    (r"Mr\.?\s+Yates\b",                    "robert_yates"),

    # ── William R. Davie ─────────────────────────────────────────────────────
    # "Davy" and "Davie" both appear in source
    (r"Mr\.?\s+Dav(?:ie?|y)\b",             "william_r_davie"),

    # ── Richard Bassett ──────────────────────────────────────────────────────
    # "Basset" (single-t) appears in source
    (r"Mr\.?\s+Basse?t+\b",                 "richard_bassett"),

    # ── Jacob Broom ──────────────────────────────────────────────────────────
    # "Broome" appears in source
    (r"Mr\.?\s+Broo?me?\b",                 "jacob_broom"),

    # ── William Houston ──────────────────────────────────────────────────────
    # Two Houston delegates attended (NJ and GA); both left early.
    # "Mr. Houston" is mapped to the Georgia delegate by convention.
    (r"Mr\.?\s+Houston\b",                  "william_houston"),

    # ── Full first+last name forms ────────────────────────────────────────────
    # Used in summary text, which is modern prose rather than 18th-century
    # address forms.  More-specific names (longer) appear first so they are
    # consumed before a shorter overlapping alternative can fire.
    (r"Charles\s+Cotesworth\s+Pinckney\b",  "charles_cotesworth_pinckney"),
    (r"Charles\s+Pinckney\b",               "charles_pinckney"),
    (r"William\s+C\.\s*Houston\b",          "william_c_houston"),
    (r"William\s+Samuel\s+Johnson\b",       "william_samuel_johnson"),
    (r"Richard\s+Dobbs\s+Spaight\b",        "richard_dobbs_spaight"),
    (r"Daniel\s+of\s+St\.\s*Thomas\s+Jenifer\b", "daniel_of_st_thomas_jenifer"),
    (r"George\s+Washington\b",              "george_washington"),
    (r"Benjamin\s+Franklin\b",              "benjamin_franklin"),
    (r"Alexander\s+Hamilton\b",             "alexander_hamilton"),
    (r"James\s+Madison\b",                  "james_madison_jr"),
    (r"Gouverneur\s+Morris\b",              "gouverneur_morris"),
    (r"Robert\s+Morris\b",                  "robert_morris"),
    (r"James\s+Wilson\b",                   "james_wilson"),
    (r"George\s+Mason\b",                   "george_mason"),
    (r"Roger\s+Sherman\b",                  "roger_sherman"),
    (r"Edmund\s+(?:J\.\s*)?Randolph\b",     "edmund_j_randolph"),
    (r"Elbridge\s+Gerry\b",                 "elbridge_gerry"),
    (r"Rufus\s+King\b",                     "rufus_king"),
    (r"William\s+Paterson\b",               "william_paterson"),
    (r"William\s+Patterson\b",              "william_paterson"),
    (r"John\s+Dickinson\b",                 "john_dickinson"),
    (r"Oliver\s+Ellsworth\b",               "oliver_ellsworth"),
    (r"John\s+Rutledge\b",                  "john_rutledge"),
    (r"Gunning\s+Bedford\b",                "gunning_bedford_jr"),
    (r"George\s+Read\b",                    "george_read"),
    (r"John\s+Langdon\b",                   "john_langdon"),
    (r"Nathaniel\s+Gorham\b",               "nathaniel_gorham"),
    (r"Hugh\s+Williamson\b",                "hugh_williamson"),
    (r"Pierce\s+Butler\b",                  "pierce_butler"),
    (r"Abraham\s+Baldwin\b",                "abraham_baldwin"),
    (r"William\s+Blount\b",                 "william_blount"),
    (r"George\s+Clymer\b",                  "george_clymer"),
    (r"Thomas\s+Fitz[Ss]im+ons?\b",         "thomas_fitzsimons"),
    (r"Jared\s+Ingersoll\b",                "jared_ingersoll"),
    (r"Thomas\s+Mifflin\b",                 "thomas_mifflin"),
    (r"James\s+McHenry\b",                  "james_mchenry"),
    (r"Luther\s+Martin\b",                  "luther_martin"),
    (r"Daniel\s+Carroll\b",                 "daniel_carroll"),
    (r"Daniel\s+Jenifer\b",                 "daniel_of_st_thomas_jenifer"),
    (r"John\s+(?:F\.\s*)?Mercer\b",         "john_f_mercer"),
    (r"William\s+Few\b",                    "william_few"),
    (r"William\s+(?:L\.\s*)?Pierce\b",      "william_l_pierce"),
    (r"Jonathan\s+Dayton\b",                "jonathan_dayton"),
    (r"William\s+Livingston\b",             "william_livingston"),
    (r"David\s+Brearly\b",                  "david_brearly"),
    (r"James\s+McClurg\b",                  "james_mcclurg"),
    (r"John\s+Blair\b",                     "john_blair"),
    (r"George\s+Wythe\b",                   "george_wythe"),
    (r"Caleb\s+Strong\b",                   "caleb_strong"),
    (r"Nicholas\s+Gilman\b",                "nicholas_gilman"),
    (r"John\s+Lansing\b",                   "john_lansing_jr"),
    (r"Robert\s+Yates\b",                   "robert_yates"),
    (r"William\s+(?:R\.\s*)?Davie\b",       "william_r_davie"),
    (r"Richard\s+Bassett\b",                "richard_bassett"),
    (r"Jacob\s+Broom\b",                    "jacob_broom"),
    (r"William\s+Houston\b",                "william_houston"),

    # ── Standalone last names ─────────────────────────────────────────────────
    # Only added where the surname is not a common English word, to avoid false
    # positives in prose.  These fire after all "Mr./Genl./Dr." patterns so the
    # titled form always wins when present.  Useful for summary text like
    # "Ellsworth then proposed…" or "Gerry objected…".
    (r"\bWilson\b",                         "james_wilson"),
    (r"\bHamilton\b",                       "alexander_hamilton"),
    (r"\bWashington\b",                     "george_washington"),
    (r"\bFranklin\b",                       "benjamin_franklin"),
    (r"\bMadison\b",                        "james_madison_jr"),
    (r"\bEllsworth\b",                      "oliver_ellsworth"),
    (r"\bElseworth\b",                      "oliver_ellsworth"),
    (r"\bSherman\b",                         "roger_sherman"),
    (r"\bMason\b",                          "george_mason"),
    (r"\bButler\b",                         "pierce_butler"),
    (r"\bMartin\b",                         "luther_martin"),
    (r"\bJohnson\b",                        "william_samuel_johnson"),
    (r"\bGerry\b",                          "elbridge_gerry"),
    (r"\bRandolph\b",                       "edmund_j_randolph"),
    (r"\bDickinson\b",                      "john_dickinson"),
    (r"\bDickenson\b",                      "john_dickinson"),
    (r"\bRutledge\b",                       "john_rutledge"),
    (r"\bRutlidge\b",                       "john_rutledge"),
    (r"\bGorham\b",                         "nathaniel_gorham"),
    (r"\bGhorum\b",                         "nathaniel_gorham"),
    (r"\bWilliamson\b",                     "hugh_williamson"),
    (r"\bSpaight\b",                        "richard_dobbs_spaight"),
    (r"\bDayton\b",                         "jonathan_dayton"),
    (r"\bBlount\b",                         "william_blount"),
    (r"\bClymer\b",                         "george_clymer"),
    (r"\bIngersoll\b",                      "jared_ingersoll"),
    (r"\bMifflin\b",                        "thomas_mifflin"),
    (r"\bMcHenry\b",                        "james_mchenry"),
    (r"\bCarroll\b",                        "daniel_carroll"),
    (r"\bJenifer\b",                        "daniel_of_st_thomas_jenifer"),
    (r"\bMercer\b",                         "john_f_mercer"),
    (r"\bDavie\b",                          "william_r_davie"),
    (r"\bBassett\b",                        "richard_bassett"),
    (r"\bBroom\b",                          "jacob_broom"),
    (r"\bGilman\b",                         "nicholas_gilman"),
    (r"\bBrearly\b",                        "david_brearly"),
    (r"\bBrearley\b",                       "david_brearly"),
    (r"\bMcClurg\b",                        "james_mcclurg"),
    (r"\bWythe\b",                          "george_wythe"),
    (r"\bLivingston\b",                     "william_livingston"),
    (r"\bLansing\b",                        "john_lansing_jr"),
    (r"\bBedford\b",                        "gunning_bedford_jr"),
    (r"\bPaterson\b",                       "william_paterson"),
    (r"\bPatterson\b",                      "william_paterson"),
    (r"\bLangdon\b",                        "john_langdon"),
    (r"\bBaldwin\b",                        "abraham_baldwin"),
    (r"\bYates\b",                          "robert_yates"),
    (r"\bPinckney\b",                       "charles_pinckney"),
    (r"\bPinkney\b",                        "charles_pinckney"),
]

# ──────────────────────────────────────────────────────────────────────────────
# Build a single combined regex from all patterns.
# Named groups p0, p1, … let the replacement function look up the delegate id.
# ──────────────────────────────────────────────────────────────────────────────

_PARTS    = [f"(?P<p{i}>{pat})" for i, (pat, _) in enumerate(RAW_PATTERNS)]
_COMBINED = re.compile("|".join(_PARTS), re.IGNORECASE)
_ID_MAP   = {f"p{i}": did for i, (_, did) in enumerate(RAW_PATTERNS)}


def _make_link(m: re.Match) -> str:
    """Replacement function: wraps the matched text in a delegate <a> tag."""
    for gname, text in m.groupdict().items():
        if text is not None:
            did = _ID_MAP[gname]
            return (
                f'<a href="attendee.html#{did}" '
                f'class="delegate-link" '
                f'data-attendee-id="{did}">{text}</a>'
            )
    return m.group(0)  # unreachable fallback


# ──────────────────────────────────────────────────────────────────────────────
# HTML processing helpers
# ──────────────────────────────────────────────────────────────────────────────

# Splits an HTML string into alternating [text, tag, text, tag, …] pieces.
# [^>]+ matches any char except >, including newlines (no re.DOTALL needed).
_TAG_RE = re.compile(r"(<[^>]+>)")

# Matches existing delegate links so we can strip them before re-processing.
_STRIP_RE = re.compile(
    r'<a\b[^>]*\bclass="delegate-link"[^>]*>(.*?)</a>',
    re.IGNORECASE | re.DOTALL,
)


def _strip_existing_links(html: str) -> str:
    """Remove any delegate links added by a previous run (idempotency)."""
    return _STRIP_RE.sub(r"\1", html)


def _apply_links(html: str) -> str:
    """
    Walk the HTML string part-by-part, applying delegate-name substitutions
    only to plain-text segments (not inside any <a> tag).
    """
    parts = _TAG_RE.split(html)
    result = []
    anchor_depth = 0  # tracks nested <a> tags (rare but safe to handle)

    for part in parts:
        if _TAG_RE.fullmatch(part):
            # It's a tag — update anchor depth and pass through unchanged
            tag_lower = part.lower()
            if re.match(r"<a[\s>]", tag_lower):
                anchor_depth += 1
            elif tag_lower.startswith("</a"):
                anchor_depth = max(0, anchor_depth - 1)
            result.append(part)
        else:
            # It's text — only substitute if we're not inside an <a>
            result.append(part if anchor_depth else _COMBINED.sub(_make_link, part))

    return "".join(result)


def process_html(html: str) -> str:
    """Full pipeline: strip old links, then apply fresh links."""
    return _apply_links(_strip_existing_links(html))


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    manifest_path = DATA / "manifest.json"
    if not manifest_path.exists():
        print("ERROR: data/manifest.json not found. Run the debate scraper first.")
        sys.exit(1)

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    # manifest.json is {"convention": …, "days": […]}
    days = manifest if isinstance(manifest, list) else manifest.get("days", [])

    stats: dict[str, int] = {}
    files_changed = 0
    files_skipped = 0

    for entry in days:
        fid   = entry.get("id", "")
        ffile = entry.get("file", f"{fid}.json")
        fpath = DATA / ffile

        if not fpath.exists():
            files_skipped += 1
            continue

        data = json.loads(fpath.read_text(encoding="utf-8"))

        # Process both contentHtml and summary — summary uses full/bare names
        # while contentHtml uses 18th-century "Mr. LastName" address forms.
        file_changed = False
        total_delta  = 0
        for field in ("contentHtml", "kingContentHtml", "summary"):
            original = data.get(field, "")
            if not original:
                continue
            new = process_html(original)
            if new == original:
                continue
            if SHOW_STATS:
                for m in re.finditer(r'data-attendee-id="([^"]+)"', new):
                    did = m.group(1)
                    stats[did] = stats.get(did, 0) + 1
            old_links = original.count("delegate-link")
            total_delta += new.count("delegate-link") - old_links
            if not DRY_RUN:
                data[field] = new
            file_changed = True

        if not file_changed:
            continue

        files_changed += 1

        if DRY_RUN:
            print(f"  [dry-run] {fid}.json  (+{total_delta} links)")
        else:
            fpath.write_text(
                json.dumps(data, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            print(f"  Updated {fid}.json  (+{total_delta} links)")

    noun = "Would update" if DRY_RUN else "Updated"
    print(f"\n{noun} {files_changed} file(s).  Skipped {files_skipped} (no contentHtml).")

    if SHOW_STATS and stats:
        print("\nDelegate link counts:")
        for did, count in sorted(stats.items(), key=lambda x: -x[1]):
            print(f"  {did:<45} {count:>4}")

    if not DRY_RUN and files_changed:
        print("\nNext step: python3 scripts/build_bundle.py")


if __name__ == "__main__":
    main()
